---
- name: 拉取前端镜像
  docker_image:
    name: "{{ frontend_image }}"
    source: pull

- name: 运行前端容器
  docker_container:
    name: frontend
    image: "{{ frontend_image }}"
    state: started
    restart_policy: always
    networks:
      - name: app-network
    ports:
      - "3000:3000"
    env:
      API_URL: "http://backend:8080"