---
- name: 运行 PostgreSQL 数据库容器
  docker_container:
    name: database
    image: huang199864/tp-devops-database:latest
    state: started
    restart_policy: always
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
    volumes:
      - db_data:/var/lib/postgresql/data