---
- name: 拉取后端镜像
  docker_image:
    name: "{{ backend_image }}"
    source: pull


- name: 运行后端应用容器
  docker_container:
    name: backend
    image: "{{ backend_image }}"
    pull: yes
    state: started
    restart_policy: always
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/{{ db_name }}"
      SPRING_DATASOURCE_USERNAME: "{{ db_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ db_password }}"
    ports:
      - "8080:8080"