---
- name: 安装依赖包
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: yes

- name: 添加 Docker GPG 密钥
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: 添加 Docker APT 仓库
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: yes

- name: 安装 Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: 启动 Docker 服务
  service:
    name: docker
    state: started
    enabled: yes

- name: 将用户添加到 docker 组
  user:
    name: admin
    groups: docker
    append: yes
